apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mssql-claim
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mssql2-claim
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 200Mi